(function(){'use strict';
var c=document.getElementById('game'),x=c.getContext('2d'),W=390,H=844,D=1,last=0,raf=0,t=0,mode='menu',paused=false,drag=false;
var panel=document.getElementById('panel'),play=document.getElementById('play'),title=document.getElementById('title'),desc=document.getElementById('desc'),pause=document.getElementById('pause'),count=document.getElementById('count'),msg=document.getElementById('message'),coinsEl=document.getElementById('coins'),gemsEl=document.getElementById('gems');
var coins=600,gems=499,G={};
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function lerp(a,b,k){return a+(b-a)*k;}function rnd(a,b){return a+Math.random()*(b-a);}function now(){return performance&&performance.now?performance.now():Date.now();}
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function rr(a,b,w,h,r,fill,stroke,lw){r=Math.min(r,w/2,h/2);x.beginPath();x.moveTo(a+r,b);x.lineTo(a+w-r,b);x.quadraticCurveTo(a+w,b,a+w,b+r);x.lineTo(a+w,b+h-r);x.quadraticCurveTo(a+w,b+h,a+w-r,b+h);x.lineTo(a+r,b+h);x.quadraticCurveTo(a,b+h,a,b+h-r);x.lineTo(a,b+r);x.quadraticCurveTo(a,b,a+r,b);x.closePath();if(fill){x.fillStyle=fill;x.fill()}if(stroke){x.strokeStyle=stroke;x.lineWidth=lw||2;x.stroke()}}
function proj(px,z){var p=clamp(1-z/1500,0,1),y=lerp(H*.1,H*1.06,Math.pow(p,1.17)),half=lerp(W*.15,W*.48,Math.pow(p,.82));return{x:W/2+px*half,y:y,s:lerp(.17,1.16,p),half:half,p:p}}
function reset(){G={distance:0,length:4700,speed:330,x:0,target:0,count:10,max:220,cool:0,battle:null,parts:[],trail:[],events:[{k:'gate',z:600,v:[2,3,4],u:0},{k:'enemy',z:1200,hp:22,m:22,u:0},{k:'gate',z:1750,v:[3,2,5],u:0},{k:'enemy',z:2350,hp:52,m:52,u:0},{k:'boss',z:2850,hp:82,m:82,u:0},{k:'gate',z:3400,v:[2,4,3],u:0},{k:'enemy',z:4050,hp:92,m:92,u:0},{k:'boss',z:4550,hp:140,m:140,u:0,final:1}]};count.textContent='10'}
function showMessage(s,color){msg.textContent=s;msg.style.color=color||'#fff';msg.style.opacity='1';clearTimeout(showMessage.tm);showMessage.tm=setTimeout(function(){msg.style.opacity='0'},800)}
function burst(px,py,color,n){for(var i=0;i<n;i++){var a=Math.random()*6.28,v=rnd(50,180);G.parts.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.3,.7),c:color,r:rnd(2,7)})}}
function start(){reset();mode='run';paused=false;panel.style.display='none';pause.style.display='block';last=now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function end(win){mode=win?'win':'lose';pause.style.display='none';panel.style.display='block';title.textContent=win?'VITÓRIA!':'DERROTA';desc.textContent=win?'Você derrotou a horda e ganhou 150 moedas e 12 gemas.':'Seu exército acabou. Pegue os multiplicadores maiores e tente novamente.';play.textContent='JOGAR NOVAMENTE';if(win){coins+=150;gems+=12;coinsEl.textContent=coins;gemsEl.textContent=gems}}
play.addEventListener('click',start);pause.addEventListener('click',function(){paused=!paused;pause.textContent=paused?'▶':'Ⅱ';if(!paused){last=now();raf=requestAnimationFrame(loop)}});
function setTarget(clientX){G.target=clamp((clientX/W-.5)*2,-.8,.8)}c.addEventListener('touchstart',function(e){drag=true;setTarget(e.touches[0].clientX);e.preventDefault()},{passive:false});c.addEventListener('touchmove',function(e){if(drag)setTarget(e.touches[0].clientX);e.preventDefault()},{passive:false});c.addEventListener('touchend',function(e){drag=false;e.preventDefault()},{passive:false});c.addEventListener('mousedown',function(e){drag=true;setTarget(e.clientX)});addEventListener('mousemove',function(e){if(drag)setTarget(e.clientX)});addEventListener('mouseup',function(){drag=false});
function update(dt){t+=dt;if(mode!=='run'||paused)return;G.cool=Math.max(0,G.cool-dt);G.x=lerp(G.x,G.target,1-Math.pow(.001,dt));if(!G.battle)G.distance+=G.speed*dt;
for(var i=0;i<G.events.length;i++){var e=G.events[i],rz=e.z-G.distance;if(e.k==='gate'&&!e.u&&rz<75&&rz>-75&&G.cool<=0){var lane=G.x<-.25?0:(G.x>.25?2:1),m=e.v[lane];G.count=Math.min(G.max,Math.floor(G.count*m));e.u=1;G.cool=.6;burst(W/2+G.x*W*.35,H*.72,'#52efff',30);showMessage('EXÉRCITO x'+m,'#62f5ff')}
if((e.k==='enemy'||e.k==='boss')&&!e.u&&rz<110){e.u=1;G.battle={e:e,hp:e.hp,tick:0};showMessage(e.k==='boss'?'CHEFE!':'BATALHA!','#ffe65a')}}
if(G.battle){var b=G.battle;b.tick-=dt;if(b.tick<=0){b.tick=.075;b.hp-=Math.max(1,Math.ceil(G.count/18));if(b.hp>0)G.count-=Math.max(1,Math.ceil(b.hp/27));burst(W/2+rnd(-60,60),H*.54+rnd(-30,30),Math.random()<.5?'#48edff':'#ff4858',5);if(G.count<=0){G.count=0;end(false);return}if(b.hp<=0){var final=!!b.e.final;coins+=b.e.k==='boss'?80:25;coinsEl.textContent=coins;G.battle=null;if(final){end(true);return}}}}
for(var p=G.parts.length-1;p>=0;p--){var q=G.parts[p];q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=100*dt;if(q.life<=0)G.parts.splice(p,1)}G.trail.push({x:W/2+G.x*W*.35,y:H*.79,life:.3});if(G.trail.length>15)G.trail.shift();for(var j=0;j<G.trail.length;j++)G.trail[j].life-=dt;count.textContent=Math.max(0,Math.floor(G.count))}
function unit(px,py,s,color,enemy){x.save();x.translate(px,py);x.shadowBlur=7;x.shadowColor='rgba(0,0,0,.28)';var g=x.createRadialGradient(-4*s,-8*s,1,0,0,17*s);g.addColorStop(0,enemy?'#ff9ca0':'#a7fcff');g.addColorStop(1,color);x.fillStyle=g;x.beginPath();x.ellipse(0,-7*s,10*s,13*s,0,0,6.28);x.fill();x.shadowBlur=0;if(enemy){x.fillStyle='#fff';x.beginPath();x.arc(-3*s,-8*s,1.5*s,0,7);x.arc(3*s,-8*s,1.5*s,0,7);x.fill()}else{x.fillStyle='#10355d';x.fillRect(-s,-20*s,2*s,8*s)}x.fillStyle=enemy?'#9f1520':'#10223e';x.beginPath();x.arc(-8*s,5*s,5*s,0,7);x.arc(8*s,5*s,5*s,0,7);x.fill();x.restore()}
function background(){var g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#9edcf8');g.addColorStop(.28,'#e0edf3');g.addColorStop(1,'#707b88');x.fillStyle=g;x.fillRect(0,0,W,H);x.globalAlpha=.16;x.fillStyle='#244b57';for(var i=0;i<16;i++){var px=i*W/15,h=80+(i*41%110),y=H*.18;x.beginPath();x.moveTo(px,y-h);x.lineTo(px-18,y);x.lineTo(px+18,y);x.closePath();x.fill()}x.globalAlpha=1}
function road(){var a=proj(0,1500),b=proj(0,0);x.beginPath();x.moveTo(a.x-a.half,a.y);x.lineTo(a.x+a.half,a.y);x.lineTo(b.x+b.half,b.y);x.lineTo(b.x-b.half,b.y);x.closePath();x.fillStyle='#bfc5cc';x.fill();x.strokeStyle='#f1f8ff';x.lineWidth=4;x.beginPath();x.moveTo(a.x-a.half,a.y);x.lineTo(b.x-b.half,b.y);x.stroke();x.beginPath();x.moveTo(a.x+a.half,a.y);x.lineTo(b.x+b.half,b.y);x.stroke();x.strokeStyle='rgba(255,255,255,.45)';x.lineWidth=3;for(var z=0;z<1500;z+=165){var zz=(z-(G.distance%165)+165)%165,p1=proj(0,zz),p2=proj(0,zz+75);x.beginPath();x.moveTo(p1.x,p1.y);x.lineTo(p2.x,p2.y);x.stroke()}}
function gates(e,rz){if(e.u||rz<-100||rz>1500)return;var p=proj(0,rz),total=p.half*1.84,lane=total/3,h=86*p.s;for(var i=0;i<3;i++){var bx=p.x-total/2+i*lane,active=(i===0&&G.x<-.25)||(i===1&&Math.abs(G.x)<=.25)||(i===2&&G.x>.25);rr(bx,p.y-h,lane-4*p.s,h,7*p.s,active?'rgba(214,48,246,.95)':'rgba(147,35,196,.82)',active?'#ff9aff':'#6a1398',3*p.s);x.fillStyle='#fff';x.strokeStyle='#11152b';x.lineWidth=6*p.s;x.font='900 '+(48*p.s)+'px Arial';x.textAlign='center';x.strokeText('x'+e.v[i],bx+(lane-4*p.s)/2,p.y-h*.35);x.fillText('x'+e.v[i],bx+(lane-4*p.s)/2,p.y-h*.35)}}
function enemies(e,rz){if(rz<-110||rz>1500)return;var hp=e.hp;if(G.battle&&G.battle.e===e)hp=Math.max(0,G.battle.hp);if(e.u&&!G.battle)return;var p=proj(0,Math.max(30,rz)),shown=Math.min(e.k==='boss'?40:55,Math.max(4,Math.floor(hp))),cols=Math.ceil(Math.sqrt(shown*1.5));for(var i=shown-1;i>=0;i--){var row=Math.floor(i/cols),col=i%cols;unit(p.x+(col-(cols-1)/2)*16*p.s,p.y-row*14*p.s,Math.max(.34,p.s*.84),'#e52633',true)}if(e.k==='boss'){x.fillStyle='#ffd817';x.beginPath();x.ellipse(p.x,p.y-70*p.s,35*p.s,29*p.s,0,0,7);x.fill();x.fillStyle='#e62b33';x.beginPath();x.ellipse(p.x-32*p.s,p.y-62*p.s,17*p.s,29*p.s,-.6,0,7);x.ellipse(p.x+32*p.s,p.y-62*p.s,17*p.s,29*p.s,.6,0,7);x.fill();var bw=155*p.s,bh=22*p.s,barx=p.x-bw/2,bary=p.y-132*p.s;rr(barx,bary,bw,bh,3*p.s,'#3d0910','#140309',3*p.s);rr(barx+3*p.s,bary+3*p.s,(bw-6*p.s)*clamp(hp/e.m,0,1),bh-6*p.s,2*p.s,'#ff3546')}}
function swarm(){var n=Math.min(G.count,75),cols=Math.ceil(Math.sqrt(n*1.28)),base=H*.79;for(var i=n-1;i>=0;i--){var row=Math.floor(i/cols),col=i%cols,inrow=Math.min(cols,n-row*cols),ox=(col-(inrow-1)/2)*15+Math.sin(t*4+i)*1.5,oy=-row*14+Math.cos(t*5+i)*1.2;unit(W/2+G.x*W*.35+ox,base+oy,Math.max(.68,1-row*.011),'#009dff',false)}}
function effects(){for(var i=0;i<G.trail.length;i++){var tr=G.trail[i];x.globalAlpha=Math.max(0,tr.life/.3)*.22;x.fillStyle='#42eaff';x.beginPath();x.arc(tr.x,tr.y,18*Math.max(0,tr.life/.3),0,7);x.fill()}x.globalAlpha=1;for(var j=0;j<G.parts.length;j++){var p=G.parts[j];x.globalAlpha=clamp(p.life/.7,0,1);x.fillStyle=p.c;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()}x.globalAlpha=1}
function render(){background();road();var list=G.events.slice().sort(function(a,b){return(b.z-G.distance)-(a.z-G.distance)});for(var i=0;i<list.length;i++){var e=list[i],rz=e.z-G.distance;if(e.k==='gate')gates(e,rz);else enemies(e,rz)}effects();swarm();rr(18,H-24,W-36,8,4,'rgba(6,15,40,.48)');rr(18,H-24,(W-36)*clamp(G.distance/G.length,0,1),8,4,'#3cecff');if(paused){x.fillStyle='rgba(3,8,22,.68)';x.fillRect(0,0,W,H);x.fillStyle='#fff';x.font='900 40px Arial';x.textAlign='center';x.fillText('PAUSADO',W/2,H/2)}}
function loop(ts){var dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);render();if(mode==='run'&&!paused)raf=requestAnimationFrame(loop)}
reset();render();})();