(()=>{
'use strict';
const wait=()=>{
 const root=window.CSManager,ui=root&&root.ui;
 if(!ui||!ui.e){setTimeout(wait,40);return}
 if(ui.__v2Installed)return;ui.__v2Installed=true;
 const css=`
 :root{--v2:#54e8ff}.topbar{background:linear-gradient(120deg,rgba(13,24,39,.99),rgba(7,18,31,.99));border-color:#294462}.brand-mark{box-shadow:0 0 28px rgba(85,232,255,.18)}
 .scoreboard{box-shadow:0 20px 52px rgba(0,0,0,.25)}.map-panel,.tactical-card,.event-card,.roster-panel,.history-panel{border-color:#28415f}
 .canvas-wrap{aspect-ratio:11/7!important;min-height:0!important;background:#040911}.map-panel{background:linear-gradient(180deg,#0c1725,#07111c)}
 .map-top-hud{top:8px;left:8px;right:8px}.alive-pill,.bomb-pill{backdrop-filter:none;background:rgba(3,8,14,.82)}
 .controls{position:relative}.controls button{min-height:39px}.event-log{scrollbar-width:thin}.plan-row{box-shadow:inset 0 1px rgba(255,255,255,.03)}
 .v2-perf{margin-left:7px;padding:6px 9px;border-radius:99px;border:1px solid #284662;background:#0a1725;color:#9bb0c8;font-size:8px;font-weight:900;letter-spacing:.08em}
 .v2-agent-card{border-radius:18px;padding:13px}.v2-agent-list{display:grid;gap:6px;max-height:208px;overflow:auto}.v2-agent{display:grid;grid-template-columns:23px 1fr auto;gap:7px;align-items:center;padding:7px;border-radius:9px;background:#091421;border:1px solid rgba(255,255,255,.045)}
 .v2-agent-icon{width:23px;height:23px;border-radius:7px;display:grid;place-items:center;color:#06111b;font-size:8px;font-weight:1000}.v2-agent-icon.t{background:var(--t)}.v2-agent-icon.ct{background:var(--ct)}.v2-agent b{display:block;font-size:9px}.v2-agent small{display:block;color:#7f91a8;font-size:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v2-agent em{font-style:normal;font-size:8px;font-weight:900;color:#9bb0c8}
 .v2-killfeed{position:absolute;right:10px;top:52px;z-index:4;display:flex;flex-direction:column;gap:5px;align-items:flex-end;pointer-events:none}.v2-kill{padding:6px 8px;border-radius:8px;background:rgba(4,9,15,.86);border:1px solid rgba(255,255,255,.08);font-size:8px;animation:v2in .2s ease-out}.v2-kill .t{color:var(--t)}.v2-kill .ct{color:var(--ct)}.v2-kill i{font-style:normal;color:#8da0b8;margin:0 5px}@keyframes v2in{from{opacity:0;transform:translateX(12px)}}
 .v2-note{font-size:8px;color:#6f849f;text-align:center;margin-top:7px}.v2-error{display:none;margin:8px 0;padding:10px;border-radius:10px;background:#35101c;border:1px solid #81334b;color:#ffb2c1;font-size:9px}.v2-error.show{display:block}
 @media(max-width:1050px){.sidebar{display:flex!important;flex-direction:column}.v2-agent-card{order:2}.event-card{order:3}}
 @media(max-width:700px){.canvas-wrap{aspect-ratio:11/7!important}.topbar{height:auto;min-height:58px}.engine-state{font-size:8px}.v2-perf{display:none}.map-panel{padding:8px}.sidebar{gap:8px}.v2-agent-list{max-height:170px}.event-log{height:210px}.bottom-grid{gap:8px}.shell{box-shadow:0 13px 38px rgba(0,0,0,.24)}}`;
 const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
 const perf=document.createElement('span');perf.className='v2-perf';perf.id='v2Perf';perf.textContent='30 FPS · OTIMIZADO';document.querySelector('.engine-state')?.appendChild(perf);
 const err=document.createElement('div');err.className='v2-error';err.id='v2Error';document.querySelector('.scoreboard')?.after(err);
 const agentCard=document.createElement('section');agentCard.className='shell v2-agent-card';agentCard.innerHTML='<div class="panel-heading compact"><div><small>DECISÕES INDIVIDUAIS</small><h3>CÉREBRO DOS AGENTES</h3></div><span class="tiny" id="v2Hz">5 Hz</span></div><div class="v2-agent-list" id="v2Agents"></div>';
 const sidebar=document.querySelector('.sidebar');if(sidebar)sidebar.insertBefore(agentCard,sidebar.lastElementChild);
 const wrap=document.querySelector('.canvas-wrap'),feed=document.createElement('div');feed.className='v2-killfeed';feed.id='v2Killfeed';wrap?.appendChild(feed);
 const note=document.createElement('div');note.className='v2-note';note.textContent='A interface desenha a 30 FPS no iPhone; o motor tático continua em passo fixo e independente.';document.querySelector('.controls')?.after(note);
 const select=document.getElementById('speedSelect');if(select){select.innerHTML='<option value="1">1×</option><option value="2">2×</option><option value="4">4×</option><option value="6">6×</option>';select.value='1'}
 const originalTable=ui.renderTable.bind(ui),originalHistory=ui.renderHistory.bind(ui),originalOnEvent=ui.onEvent.bind(ui);
 ui.__v2={lastHud:0,lastMap:0,lastTable:0,lastHistory:-1,lastFrame:performance.now(),acc:0,frames:0,fpsAt:performance.now(),fps:30,tracers:[],bg:null};
 ui.onEvent=function(ev){originalOnEvent(ev);if(ev.type==='kill'){const players=this.e.teams.flatMap(t=>t.players),a=players.find(p=>p.n===ev.killer),b=players.find(p=>p.n===ev.victim);if(a&&b)this.__v2.tracers.push({a:{...a.pos},b:{...b.pos},life:1,color:a.side==='T'?'#f1b93e':'#49a8ff'});const row=document.createElement('div');row.className='v2-kill';row.innerHTML=`<b class="${ev.side==='T'?'t':'ct'}">${ev.killer}</b><i>${ev.weapon||'◼'}</i><b>${ev.victim}</b>`;feed.prepend(row);while(feed.children.length>4)feed.lastChild.remove();setTimeout(()=>row.remove(),5000)}};
 ui.loop=function(t){try{const v=this.__v2,dt=Math.min(.1,(t-v.lastFrame)/1000);v.lastFrame=t;if(this.e.running&&!this.e.matchEnded){v.acc+=dt*this.e.speed;let n=0;while(v.acc>=.2&&n++<6){this.e.tick(.2);v.acc-=.2}if(n>=6&&v.acc>.7)v.acc=.2}this.render(t,dt);v.frames++;if(t-v.fpsAt>=1000){v.fps=Math.round(v.frames*1000/(t-v.fpsAt));v.frames=0;v.fpsAt=t;perf.textContent=`${v.fps} FPS · ${matchMedia('(max-width:700px)').matches?'IPHONE':'BALANCEADO'}`}}catch(e){this.e.running=false;err.classList.add('show');err.textContent='O motor foi pausado por segurança: '+(e.message||e);console.error(e)}requestAnimationFrame(x=>this.loop(x))};
 ui.render=function(now=performance.now(),dt=0){const v=this.__v2,s=this.e.snapshot();if(now-v.lastMap>33){this.renderMap(s,dt);v.lastMap=now}if(now-v.lastHud>150){const A=this.e.teams[0],B=this.e.teams[1];this.q('engineState').querySelector('span').textContent=this.e.matchEnded?'PARTIDA ENCERRADA':this.e.running?'MOTOR EXECUTANDO':'MOTOR PAUSADO';this.q('teamAName').textContent=A.name;this.q('teamBName').textContent=B.name;this.q('teamAScore').textContent=A.score;this.q('teamBScore').textContent=B.score;this.q('teamASide').textContent=A.side==='T'?'TERRORISTAS':'CONTRATERRORISTAS';this.q('teamBSide').textContent=B.side==='T'?'TERRORISTAS':'CONTRATERRORISTAS';this.q('teamAEconomy').textContent=fmtMoney(A.avgMoney())+' · '+A.buyType;this.q('teamBEconomy').textContent=fmtMoney(B.avgMoney())+' · '+B.buyType;this.q('roundLabel').textContent=`ROUND ${s.roundNo} · ${s.overtime?'PRORROGAÇÃO':s.half===1?'PRIMEIRO TEMPO':'SEGUNDO TEMPO'}`;this.q('roundClock').textContent=fmtTime(s.roundTime);this.q('phaseLabel').textContent=s.phase;this.q('seriesLabel').textContent=s.overtime?'MR3 · PRORROGAÇÃO':'MR12 · PRIMEIRO A 13';this.q('tAlive').textContent=s.T.alive().length;this.q('ctAlive').textContent=s.CT.alive().length;this.q('bombState').textContent=s.bombPlanted?`${s.bombSite} · ${fmtTime(s.roundTime)}`:this.e.bombCarrier?this.e.bombCarrier.n:this.e.bombGroundNode?'CAÍDA':'COM T';this.q('bombPill').classList.toggle('planted',s.bombPlanted);const p=Math.round(s.winT*100);this.q('leftProb').textContent=p+'%';this.q('rightProb').textContent=(100-p)+'%';this.q('winProbBar').style.width=p+'%';this.q('tPlan').textContent=this.planName(s.T.plan);this.q('ctPlan').textContent=this.planName(s.CT.plan);this.q('tConfidence').textContent=s.T.planConfidence+'%';this.q('ctConfidence').textContent=s.CT.planConfidence+'%';this.q('tInfo').textContent=s.infoT+'%';this.q('ctInfo').textContent=s.infoCT+'%';const control=this.control();this.q('mapControl').textContent=control;this.q('advantage').textContent=p>58?'TERRORISTAS':p<42?'CONTRATERRORISTAS':'EQUILÍBRIO';this.q('analysisText').textContent=this.analysis(s,control);this.renderV2Agents(s);document.getElementById('v2Hz').textContent=Math.round(5*this.e.speed)+' Hz';v.lastHud=now}if(now-v.lastTable>500){originalTable();v.lastTable=now}if(v.lastHistory!==s.history.length||s.matchEnded){originalHistory(s);v.lastHistory=s.history.length}};
 ui.renderV2Agents=function(s){const list=document.getElementById('v2Agents');if(!list)return;const ps=[...s.T.alive(),...s.CT.alive()].sort((a,b)=>(b.engaged-a.engaged)||(b.skill-a.skill)).slice(0,8);const html=ps.map(p=>`<div class="v2-agent"><div class="v2-agent-icon ${p.side.toLowerCase()}">${p.n[0]}</div><div><b>${p.n} · ${ROLE_LABEL[p.role]}</b><small>${p.intent||'LENDO O MAPA'}</small></div><em>${Math.round(p.hp)} HP</em></div>`).join('');if(list.dataset.h!==html){list.dataset.h=html;list.innerHTML=html}};
 ui.buildV2Background=function(){const W=this.c.width,H=this.c.height,b=document.createElement('canvas');b.width=W;b.height=H;const c=b.getContext('2d',{alpha:false}),sx=W/100,sy=H/100;c.fillStyle='#040911';c.fillRect(0,0,W,H);const g=c.createRadialGradient(W*.52,H*.43,35,W*.5,H*.5,W*.75);g.addColorStop(0,'#14263d');g.addColorStop(1,'#050a11');c.fillStyle=g;c.fillRect(0,0,W,H);const rooms=[[[3,39],[19,38],[23,48],[22,63],[5,66]],[[25,14],[52,4],[58,20],[45,34],[30,32]],[[57,7],[98,5],[99,33],[78,39],[59,29]],[[28,36],[72,34],[75,57],[56,70],[28,65]],[[25,67],[54,66],[61,97],[27,97]],[[57,58],[98,55],[99,96],[60,98]]];c.lineJoin='round';for(const poly of rooms){c.beginPath();poly.forEach(([x,y],i)=>i?c.lineTo(x*sx,y*sy):c.moveTo(x*sx,y*sy));c.closePath();c.fillStyle='rgba(18,33,51,.88)';c.fill();c.strokeStyle='rgba(81,111,145,.28)';c.lineWidth=2;c.stroke()}for(const[a,z]of MAP.edges){const A=MAP.nodes[a],B=MAP.nodes[z];c.strokeStyle='rgba(83,111,143,.28)';c.lineWidth=15;c.beginPath();c.moveTo(A.x*sx,A.y*sy);c.lineTo(B.x*sx,B.y*sy);c.stroke();c.strokeStyle='rgba(153,181,210,.13)';c.lineWidth=2;c.stroke()}for(const n of Object.values(MAP.nodes)){c.beginPath();c.arc(n.x*sx,n.y*sy,n.site?24:13,0,Math.PI*2);c.fillStyle=n.site?(n.site==='A'?'rgba(241,185,62,.17)':'rgba(73,168,255,.17)'):'rgba(8,17,28,.94)';c.fill();c.strokeStyle=n.site?(n.site==='A'?'rgba(241,185,62,.72)':'rgba(73,168,255,.72)'):'rgba(85,117,151,.45)';c.lineWidth=1.5;c.stroke();c.fillStyle='#8195ae';c.font='700 10px system-ui';c.textAlign='center';c.fillText(n.n,n.x*sx,n.y*sy+(n.site?36:26))}this.__v2.bg=b};
 ui.renderMap=function(s,dt=0){const c=this.ctx,W=this.c.width,H=this.c.height,sx=W/100,sy=H/100,v=this.__v2;if(!v.bg||v.bg.width!==W)this.buildV2Background();c.drawImage(v.bg,0,0);for(const sm of s.smokes){const n=MAP.nodes[sm.node],r=21+Math.sin(performance.now()/260)*2;c.fillStyle='rgba(174,190,204,.29)';c.beginPath();c.arc(n.x*sx,n.y*sy,r,0,Math.PI*2);c.fill()}for(const f of s.fires){const n=MAP.nodes[f.node];c.fillStyle='rgba(255,106,55,.37)';c.beginPath();c.arc(n.x*sx,n.y*sy,22,0,Math.PI*2);c.fill()}for(const team of this.e.teams)for(const p of team.players)this.drawV2Player(p,sx,sy);v.tracers.forEach(t=>t.life-=dt*2.4);v.tracers=v.tracers.filter(t=>t.life>0);for(const t of v.tracers){c.globalAlpha=t.life;c.strokeStyle=t.color;c.lineWidth=2;c.beginPath();c.moveTo(t.a.x*sx,t.a.y*sy);c.lineTo(t.b.x*sx,t.b.y*sy);c.stroke();c.globalAlpha=1}if(this.e.bombCarrier?.alive){const p=this.e.bombCarrier.pos;this.drawBomb(p.x*sx+8,p.y*sy-8)}else if(s.bombPlanted){const n=MAP.nodes[s.bombSite==='A'?'AS':'BS'];this.drawBomb(n.x*sx,n.y*sy)}else if(this.e.bombGroundNode){const n=MAP.nodes[this.e.bombGroundNode];this.drawBomb(n.x*sx,n.y*sy)}};
 ui.drawV2Player=function(p,sx,sy){const c=this.ctx,pos=p.pos,x=pos.x*sx,y=pos.y*sy,color=p.side==='T'?'#f1b93e':'#49a8ff',r=p.role==='AWP'?10:8;c.globalAlpha=p.alive?1:.18;c.shadowColor=color;c.shadowBlur=p.alive?8:0;c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle='#03101a';c.lineWidth=2;c.stroke();c.fillStyle='#04111b';c.font='1000 7px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(p.n[0],x,y+.3);c.fillStyle='#e3edf9';c.font='800 9px system-ui';c.textBaseline='alphabetic';c.fillText(p.n,x,y-r-5);if(p.alive&&p.hp<100){c.fillStyle='#142335';c.fillRect(x-10,y+r+4,20,2.5);c.fillStyle=p.hp>40?'#55ef9e':'#ff607d';c.fillRect(x-10,y+r+4,20*p.hp/100,2.5)}if(p.flash>0){c.strokeStyle='#fff';c.lineWidth=2;c.beginPath();c.arc(x,y,r+4,0,Math.PI*2);c.stroke()}c.globalAlpha=1};
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&ui.e.running){ui.e.setRunning(false);ui.q('playBtn').textContent='▶ CONTINUAR';ui.q('engineState').querySelector('span').textContent='PAUSADO PELO IPHONE'}ui.__v2.acc=0;ui.__v2.lastFrame=performance.now()});
 ui.render(performance.now(),0);
};wait();
})();
